server:
  port: 8011

spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: qinjiyuan
    password: Radiant123
    listener:
      simple:
        acknowledge-mode: Auto #自动ack进行订单的校验，还有其他的两种类型 Manual None



messageQueue:
  exchangeDirectName: amq.direct
  exchangeTopicName: amq.topic
  exchangeFanoutName: amq.fanout
  bindingDirectKey: mydirectkey
  bindingTopicKey: mytopickey.*
  bindingFanoutKey: myfanoutkey


queues:
  direct:
    info: direct.info
    error: direct.error
    info-routing-key: direct-info-key
    error-routing-key: direct-error-key



  topic: topic.info
  fanout: fanout.info