server:
  port: 8011

spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 10.0.75.1
    port: 5672
    username: qinjiyuan
    password: Radiant123
    listener:
      simple:
        acknowledge-mode: Auto #自动ack进行订单的校验，还有其他的两种类型 Manual None



messageQueue:
  exchangeDirectName: amq.direct
  exchangeTopicName: amq.topic
  exchangeFanoutName: amq.fanout
  bindingDirectKey: mydirectkey
  bindingTopicKey: mytopickey.*
  bindingFanoutKey: myfanoutkey


queues:
  direct: direct.info
  topic: topic.info
  fanout: fanout.info